#! /usr/bin/env python

import sys
sys.path += ['../utils']
from sconsutils import *

libCommon = makeLib('common', ['env.c', 'stringtable.c', 'error.c', 'mem.c'])
#lc = (None, libCommon)
lc = ('.', 'common')

setDeps(['test.c', lc], ['util.c', lc])

makeProg('test', ['test.c', 'util.c'])
