#! /usr/bin/env python

import sys
sys.path += ['../utils']
from sconsutils import *

setDeps(['node.c', ('../common', 'common')])

makeProg('test_allocator', ['test_allocator.c', 'allocator.c'])
makeProg('test_heap', ['test_heap.c', 'heap.c', 'allocator.c', 'node.c'])
